[package]
authors = ["Rimpampa <riccardo.ripanti01@gmail.com>"]
edition = "2021"
name = "pcp"
version = "0.1.0"
[dependencies]
rand = "0.8.4"

[dependencies.tokio]
features = ["time", "sync", "rt", "macros", "net"]
version = "1"

[dev-dependencies.tokio]
features = ["rt-multi-thread"]